class AppRouteName {
  static const splash = 'splash';
  static const recentFiles = 'recentFiles';
  static const onboarding = 'onboarding';
  static const onboardingShell = 'onboardingShell';
  static const shell = 'hostel_shell';
  static const home = 'home';
  static const filesRoot = 'files.root';
  static const filesFolder = 'files.folder';
  static const filesSearch = 'files.search';
  static const settings = 'settings';
  static const showPdf = 'pdf.view';
  static const mergePdf = 'pdf.merge';
  static const protectPdf = 'pdf.protect';
  static const unlockPdf = 'pdf.unlock';
  static const compressPdf = 'pdf.compress';
  static const pdfToImage = 'pdf.toImage';
  static const imagesToPdf = 'images.toPdf';
  static const reorderPdf = 'pdf.reorder';
  static const splitPdf = 'pdf.split';
  static const pdfViewer = 'pdf.viewer';
  static const signPdf = 'pdf.sign';
  static const filesRootFullscreen = 'files.root.fullscreen';
  static const filesFolderFullScreen = 'files.folder.fullscreen';
  static const filesSearchFullscreen = 'files.search.fullscreen'; // NEW
  static const folderPickScreen = 'folder.picker';
  static const recentFilesSearch = 'recentFiles.search';
  static const recentFilesFullscreen = 'recentFiles.fullscreen';
  static const recentFilesSearchFullscreen = 'recentFiles.search.fullscreen';
}
